export const myteam = {
  // upm -- team
  "UPM Team": {
    //title: "Associate Professors",
    members: [
      {
        name: "Pedro Reviriego",
        position: "(IP1)",
        roleTranslationKey: "team.professorCards.roles.1",
        description:
          "Pedro Reviriego received the M.Sc. and Ph.D. degrees in telecommunications engineering from the Technical University of Madrid, Madrid, Spain, in 1994 and 1997, respectively. From 1997 to 2000, he was an Engineer with Teldat, Madrid, working on router implementation. In 2000, he joined Massana to work on the development of 1000BASE-T transceivers. From 2004 to 2007, he was a Distinguished Member of Technical Staff with the LSI Corporation, working on the development of Ethernet transceivers. From 2007 to 2018 he was with Nebrija University, from 2018 to 2022 with Universidad Carlos III de Madrid. He is currently with Universidad Politécnica de Madrid working on probabilistic data structures, high speed packet processing and machine learning.",
        img: "assets/img/team/pedro-reviriego.jpg",
        email: "pedro.reviriego@upm.es",
        center: "E.T.S. de ingenieros de telecomunicacion",
        key: "8",
      },
      // {
      //   name: "Juan Quemada",
      //   position: "",
      //   roleTranslationKey: "team.professorCards.roles.1",
      //   description:
      //     "Juan Quemada leads the Next Generation Internet Group within the Telematics Engineering Department, Universidad Politécnica de Madrid (UPM), where he is Full Professor. He is also the Telefonica Chair of UPM, for the next-generation Internet, and the UPM Representative at the World Wide Web Consortium. His research interests include collaborative and social application architecture for the Internet and the Web, including cloud computing, where he has a strong involvement in European and Spanish research.",
      //   img: "assets/img/team/juan-quemada.jpg",
      //   github: "https://github.com/jquemada",
      //   email: "juan.quemada@upm.es",
      //   center: "E.T.S. de ingenieros de telecomunicacion",
      //   key: "1",
      // },
      {
        name: "Enrique Barra",
        // position: "team.professorCards.positions.1",
        position: "(IP2)",
        roleTranslationKey: "team.professorCards.roles.2",
        description:
          "Enrique Barra is a professor at Telematic Engineering Department, School of Telecommunications Engineering. He received the Ph.D. degree in Telematic Engineering with minoring in Multimedia and Technology Enhanced Learning from  Universidad Politécnica de Madrid (UPM).He has participated in many European projects, such as GLOBAL, FIWARE, and C@R. He is currently involved in several projects contributing to the generation and distribution of educational content in TEL environments. His research interests include videoconferencing, games in education, and social networks in education.",
        img: "assets/img/team/enrique-barra.jpg",
        github: "https://github.com/ebarra",
        email: "enrique.barra@upm.es",
        center: "E.T.S. de ingenieros de telecomunicacion",
        key: "5",
      },
      {
        name: "Álvaro Alonso",
        position: "",
        roleTranslationKey: "team.professorCards.roles.2",
        description:
          "Álvaro Alonso, Ph.D. in Telecommunications Engineering, Professor at the Telematic Systems Engineering Department, School of Telecommunications Engineering, is a WebHTML5 Videoconference and Cloud Computing expert.He is the author of several articles and participates in a lot of Spanish and European research projects. His research interests include multi-conferencing systems in cloud computing, security, and the IoT in the future Internet.",
        img: "assets/img/team/alvaro-alonso.jpg",
        github: "https://github.com/aalonsog",
        email: "alvaro.alonso@upm.es",
        center: "E.T.S. de ingenieros de telecomunicacion",
        key: "6",
      },
      {
        name: "Aldo Gordillo",
        position: "",
        roleTranslationKey: "team.professorCards.roles.2",
        description:
          "Aldo Gordillo received the degree in Telecommunications Engineering and the PhD degree in Telematics Engineering from UPM, in 2012 and 2017, respectively. From 2012 to 2017, he was a Research and Development Engineer with the Telematics Engineering Department, UPM. He is currently an Assistant Professor with the Computer Science Department, also at UPM. His research interests include the field of technology-enhanced learning, with a special focus on creation, evaluation, and dissemination of e-learning resources, computer science education, game-based learning, and e-learning systems.",
        img: "assets/img/team/aldo-gordillo.jpg",
        github: "https://github.com/agordillo",
        email: "a.gordillo@upm.es",
        center: "E.T.S de ing. de sistemas informáticos",
        key: "7",
      },
      {
        name: "Gabriel Huecas",
        position: "",
        roleTranslationKey: "team.professorCards.roles.1",
        description:
          "Gabriel Huecas, Ph.D in Telecommunications Engineering, is currently the Postgraduate Assistant Director at the School of Telecommunications Engineering of Universidad Politécnica de Madrid (UPM), as well as a professor at the same institution. He is the author of different Java 2 programming books.",
        img: "assets/img/team/gabriel-huecas.jpg",
        github: "https://github.com/ghuecas",
        email: "gabriel.huecas@upm.es",
        center: "E.T.S. de ingenieros de telecomunicacion",
        key: "4",
      },
      {
        name: "Joaquín Salvachúa",
        position: "",
        roleTranslationKey: "team.professorCards.roles.1",
        description:
          "Joaquín Salvachúa is a professor at UPM, where he received the M.Sc., Ph.D. in Telecommunications Engineering. He is also FIWARE Technical Steering Committee member elected as Remarkable individuals. His research interests include advanced cloud and edge architectures, big data infrastructure, data privacy and usage control, NoSql databases, applications, and identity in blockchain.",
        img: "assets/img/team/joaquin-salvachua.jpg",
        github: "https://github.com/jsalvachua",
        email: "joaquin.salvachua@upm.es",
        center: "E.T.S. de ingenieros de telecomunicacion",
        key: "2",
      },
      {
        name: "Santiago Pavón",
        roleTranslationKey: "team.professorCards.roles.1",
        position: "",
        description:
          "Santiago Pavón Gómez obtained the B.S. and Ph.D. in Telecommunication Engineer from the Universidad Politécnica de Madrid (UPM) in 1987 and 1990 respectively. Santiago obtained the position of Assistant Professor in 1991 and the position of Associate Professor in 1992. He has published several articles and participated in national and international research projects related to Formal Description Techniques, CSCW, Tele-Education, collaboration services, IPv6, virtualization, identity services, safely (Cyspa) and Blockchain (BAPI).",
        img: "assets/img/team/santiago-pavon.jpg",
        github: "https://github.com/sanpago",
        email: "santiago.pavon@upm.es",
        center: "E.T.S. de ingenieros de telecomunicacion",
        key: "3",
      },
      {
        name: "Jose Andres Muñoz",
        position: "",
        roleTranslationKey: "team.professorCards.roles.6",
        description:
          "Andrés received the B.S. in Telematic Engineering from Escuela Superior Politécnica del Litoral (ESPOL) in 2013 He received the M.Sc. in Telematic Services and Network Engineering from Universidad Politécnica de Madrid (UPM). Andrés is currently a Ph.D. student in Telecommunications Engineering and a Researcher with the Next Generation Internet Research Group. His previous experience includes Telematic Laboratories Coordination or Servers and Communications Assistant, both in ESPOL.Andres has carried out different research projects, such as Web Platform Development for Control and Monitoring of Environmental Parameters in Agriculture or Kiswar Proyect Reactive Evacuation Management Systemsfor Emergency Situations.",
        img: "assets/img/team/jose-andres-munoz.jpg",
        github: "https://github.com/anmunoz",
        email: "joseandres.munoz@upm.es",
        center: "E.T.S. de ingenieros de telecomunicacion",
        key: "9",
      },
      {
        name: "Alejandro Pozo",
        position: "",
        roleTranslationKey: "team.professorCards.roles.6",
        description:
          "Researcher and Ph.D. student at Politécnica of Madrid (UPM). He received the M.Sc. in Telecommunications Engineering from the UPM, Spain, in 2017, where he is currently pursuing the Ph.D. in Telecommunications Engineering and is a Research Assistant with the Next Generation Internet Research Group. He participates in several European projects and publishes results in journals related to the Internet of Things, security, and identity management.",
        img: "assets/img/team/alejandro-pozo.jpg",
        github: "https://github.com/apozohue10",
        email: "alejandro.pozo@upm.es",
        center: "E.T.S. de ingenieros de telecomunicacion",
        key: "10",
      },
  
      {
        name: "Carlos Arriaga",
        position: "",
        roleTranslationKey: "team.professorCards.roles.3",
        description:
          " Carlos is a Ph.D. student in Telecommunication Engineering at Universidad Politécnica de Madrid (UPM).  He received the B.S. and M.Sc. in Telecommunications Engineering from UPM in 2020 and 2022. His research interests lie in primarily in the field of video-conference scalability and WebRTC.",
        img: "assets/img/team/carlos-arriaga.jpg",
        github: "https://github.com/Arri98",
        email: "carlos.arriaga.prieto@upm.es",
        center: "E.T.S. de ingenieros de telecomunicacion",
        key: "13",
      },
      {
        name: "Javier Conde",
        position: "",
        roleTranslationKey: "team.professorCards.roles.6",
        description:
          "PhD student in Telematics Engineering at UPM and researcher in the Department of Telematics Engineering. He received the B.S. and M.Sc. in Telecommunications Engineering from UPM in 2018 and 2020. His research interests lie in the fields of Open Linked Data, Digital Twins, Big Data and Machine Learning.",
        img: "assets/img/team/javier-conde.jpg",
        github: "https://github.com/javicond3",
        email: "javier.conde.diaz@upm.es",
        center: "E.T.S. de ingenieros de telecomunicacion",
        key: "11",
      },
      {
        name: "Carlos Aparicio",
        position: "",
        roleTranslationKey: "team.professorCards.roles.3",
        description: "",
        img: "assets/img/team/carlos-aparicio.jpeg",
        github: "",
        email: "",
        center: "E.T.S. de ingenieros de telecomunicacion",
        key: "30",
      },
    
    ],
  },
};
