export const mytools = [
  {
    img: "assets/img/logos/sgame.svg",
    route: "https://sgame.etsisi.upm.es/",
    title: "SGAME",
    description: "descripción de la herramienta",
    translationKey: "tools.toolCards.description.1",
    github: "https://github.com/CyberAula/sgame_platform",
    key:"1",
  },
  {
    img: "assets/img/logos/escapp.svg",
    route: "https://escape.dit.upm.es/",
    title: "Educational Escape Rooms", 
    description: "descripciónde la herramienta",
    translationKey: "tools.toolCards.description.2",
    github: "https://github.com/ging/escapp",
    key:"2",
  },
  {
    img: "assets/img/logos/school.svg",
    route: "https://cyberaula.github.io/quiz-converter/",
    title: "QUIZ converter",
    description: "descripciónde la herramienta",
    translationKey: "tools.toolCards.description.3",
    github: "https://github.com/CyberAula/quiz-converter",
    key:"3",
  
  },
  {
    img: "assets/img/logos/school.svg",
    route: "https://sonsoles.me/RESCORM-quiz-generator/",
    title: "RESCORM Quiz generator",
    description: "descripciónde la herramienta",
    translationKey: "tools.toolCards.description.4",  
    github: "https://github.com/sonsoleslp/RESCORM-quiz-generator",
    key:"4",
  },
  {
    img: "assets/img/logos/codeditor.png",
    route: "https://github.com/agordillo/CODEditor",
    title: "CODEditor",
    description: "descripciónde la herramienta",
    translationKey: "tools.toolCards.description.3",
    github: "https://github.com/agordillo/CODEditor",
    key:"5",
  },
  {
    img: "assets/img/logos/loep.svg",
    route: "https://github.com/agordillo/LOEP",
    title: "LOEP",
    description: "descripciónde la herramienta",
    translationKey: "tools.toolCards.description.3",
    github: "https://github.com/agordillo/LOEP",
    key:"6",
  },
  {
    img: "assets/img/logos/europeana.png",
    route: "https://github.com/agordillo/EuropeanaRS",
    title: "EuropeanaRS",
    description: "descripciónde la herramienta",
    translationKey: "tools.toolCards.description.3",
    github: "https://github.com/agordillo/EuropeanaRS",
    key:"7",
  },
 
  {
    img: "assets/img/logos/rescorm.svg",
    route: "https://github.com/agordillo/RESCORM",
    title: "RESCORM",
    description: "descripciónde la herramienta",
    translationKey: "tools.toolCards.description.3",
    github: "https://github.com/agordillo/RESCORM",
    key:"8",
  },

];
