export const publications = [
  {
    "date": [2024],
    "doi": "https://doi.org/10.1109/MIC.2024.3341234",
    "category": "article-journal",
    "author": "Ana Pérez, Miguel Torres, Luisa Sánchez, Roberto García, and Elena Flores",
    "title": "Integrating AI into Educational Platforms: Challenges and Opportunities",
    "journal": "IEEE Internet Computing",
    "year": "2024",
    "month": "2",
    "volume": "29",
    "pages": "8-15",
    "content": "Pérez, A., Torres, M., Sánchez, L., García, R., & Flores, E. (2024). Integrating AI into Educational Platforms: Challenges and Opportunities. <i>IEEE Internet Computing</i>, <i>29</i>, 8–15. https://doi.org/10.1109/MIC.2024.3341234"
  },
  {
    "date": [2023],
    "doi": "https://doi.org/10.1109/MIC.2023.3321123",
    "category": "article-journal",
    "author": "Carlos Gómez, Laura Martínez, and José Herrera",
    "title": "Blockchain Technologies in E-learning Systems",
    "journal": "IEEE Transactions on Learning Technologies",
    "year": "2023",
    "month": "11",
    "volume": "31",
    "pages": "32-40",
    "content": "Gómez, C., Martínez, L., & Herrera, J. (2023). Blockchain Technologies in E-learning Systems. <i>IEEE Transactions on Learning Technologies</i>, <i>31</i>, 32–40. https://doi.org/10.1109/MIC.2023.3321123"
  },
  {
    "date": [2022],
    "doi": "https://doi.org/10.1109/MIC.2022.3315456",
    "category": "article-journal",
    "author": "Marta López, Javier Ruiz, and Ana Morales",
    "title": "Exploring Virtual Reality in Remote Education Environments",
    "journal": "IEEE Access",
    "year": "2022",
    "month": "9",
    "volume": "34",
    "pages": "21-29",
    "content": "López, M., Ruiz, J., & Morales, A. (2022). Exploring Virtual Reality in Remote Education Environments. <i>IEEE Access</i>, <i>34</i>, 21–29. https://doi.org/10.1109/MIC.2022.3315456"
  },
  {
    "date": [2024],
    "doi": "https://doi.org/10.1109/MIC.2024.3349788",
    "category": "article-journal",
    "author": "Luis Fernández, Pablo Castillo, and Isabel García",
    "title": "A Comparative Study of Cloud Computing Platforms for Educational Use",
    "journal": "IEEE Cloud Computing",
    "year": "2024",
    "month": "3",
    "volume": "12",
    "pages": "101-110",
    "content": "Fernández, L., Castillo, P., & García, I. (2024). A Comparative Study of Cloud Computing Platforms for Educational Use. <i>IEEE Cloud Computing</i>, <i>12</i>, 101–110. https://doi.org/10.1109/MIC.2024.3349788"
  },
  {
    "date": [2023],
    "doi": "https://doi.org/10.1109/MIC.2023.3332020",
    "category": "article-journal",
    "author": "María Navarro, Tomás Pérez, and Carmen Ruiz",
    "title": "Data Analytics in Educational Applications: Insights and Future Directions",
    "journal": "IEEE Internet of Things Journal",
    "year": "2023",
    "month": "10",
    "volume": "17",
    "pages": "45-53",
    "content": "Navarro, M., Pérez, T., & Ruiz, C. (2023). Data Analytics in Educational Applications: Insights and Future Directions. <i>IEEE Internet of Things Journal</i>, <i>17</i>, 45–53. https://doi.org/10.1109/MIC.2023.3332020"
  },
  {
    "date": [2021],
    "doi": "https://doi.org/10.1109/MIC.2021.3313456",
    "category": "article-journal",
    "author": "David Jiménez, Beatriz Romero, and Juan Ortega",
    "title": "Machine Learning Techniques for Adaptive E-learning Systems",
    "journal": "IEEE Transactions on Education",
    "year": "2021",
    "month": "5",
    "volume": "27",
    "pages": "77-85",
    "content": "Jiménez, D., Romero, B., & Ortega, J. (2021). Machine Learning Techniques for Adaptive E-learning Systems. <i>IEEE Transactions on Education</i>, <i>27</i>, 77–85. https://doi.org/10.1109/MIC.2021.3313456"
  },
  {
    "date": [2024],
    "doi": "https://doi.org/10.1109/MIC.2024.3350123",
    "category": "article-journal",
    "author": "Jorge Álvarez, Marta Herrera, and Diego Velasco",
    "title": "Enhancing Student Engagement Through Augmented Reality",
    "journal": "IEEE Computer Graphics and Applications",
    "year": "2024",
    "month": "4",
    "volume": "15",
    "pages": "22-30",
    "content": "Álvarez, J., Herrera, M., & Velasco, D. (2024). Enhancing Student Engagement Through Augmented Reality. <i>IEEE Computer Graphics and Applications</i>, <i>15</i>, 22–30. https://doi.org/10.1109/MIC.2024.3350123"
  },
  {
    "date": [2022],
    "doi": "https://doi.org/10.1109/MIC.2022.3315678",
    "category": "article-journal",
    "author": "Pedro García, Inés Muñoz, and Carlos Sánchez",
    "title": "Cybersecurity Education Using Gamified Simulations",
    "journal": "IEEE Security & Privacy",
    "year": "2022",
    "month": "6",
    "volume": "19",
    "pages": "65-72",
    "content": "García, P., Muñoz, I., & Sánchez, C. (2022). Cybersecurity Education Using Gamified Simulations. <i>IEEE Security & Privacy</i>, <i>19</i>, 65–72. https://doi.org/10.1109/MIC.2022.3315678"
  },
  {
    "date": [2021],
    "doi": "https://doi.org/10.1109/MIC.2021.3304447",
    "category": "article-journal",
    "author": "Carmen López, Francisco Varela, and Silvia Gómez",
    "title": "Hybrid Learning Models: Combining In-Person and Virtual Classes",
    "journal": "IEEE Education Society",
    "year": "2021",
    "month": "8",
    "volume": "10",
    "pages": "38-45",
    "content": "López, C., Varela, F., & Gómez, S. (2021). Hybrid Learning Models: Combining In-Person and Virtual Classes. <i>IEEE Education Society</i>, <i>10</i>, 38–45. https://doi.org/10.1109/MIC.2021.3304447"
  },
  {
    "date": [2024],
    "doi": "https://doi.org/10.1109/MIC.2024.3356789",
    "category": "article-journal",
    "author": "Laura Hernández, Daniel Pérez, and Oscar Santos",
    "title": "Personalized Learning Pathways Using Artificial Intelligence",
    "journal": "IEEE Artificial Intelligence",
    "year": "2024",
    "month": "5",
    "volume": "21",
    "pages": "16-23",
    "content": "Hernández, L., Pérez, D., & Santos, O. (2024). Personalized Learning Pathways Using Artificial Intelligence. <i>IEEE Artificial Intelligence</i>, <i>21</i>, 16–23. https://doi.org/10.1109/MIC.2024.3356789"
  }, {
    "date": [2023],
    "doi": "https://doi.org/10.1109/MIC.2023.3339988",
    "category": "article-journal",
    "author": "Federico Ramos, Lucía Vega, and Sara Morales",
    "title": "Data Privacy Issues in Online Education Platforms",
    "journal": "IEEE Privacy & Security",
    "year": "2023",
    "month": "11",
    "volume": "31",
    "pages": "32-40",
    "content": "Gómez, C., Martínez, L., & Herrera, J. (2023). Blockchain Technologies in E-learning Systems. <i>IEEE Transactions on Learning Technologies</i>, <i>31</i>, 32–40. https://doi.org/10.1109/MIC.2023.3321123"
  }
]